version: 2
jobs:
  buildAndDeploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Push to s3
          command: aws s3 sync . s3://louisborsu.be --region eu-west-1 --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              only: master
